#include QMK_KEYBOARD_H

/* THIS FILE WAS GENERATED!
 *
 * This file was generated by qmk json2c. You may or may not want to
 * edit it directly.
 */

// extra key defines that can be used in the keymap
enum plaid_keycodes {
  JSARROW = SAFE_RANGE
 };

const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {
  /* base */
	[0] = LAYOUT_plaid_mit(KC_TAB, KC_Q, KC_W, KC_E, KC_R, KC_T, KC_Y, KC_U, KC_I, KC_O, KC_P, KC_BSPC, LT(4,KC_ESC), KC_A, LT(5,KC_S), LT(9,KC_D), LSFT_T(KC_F), LT(7,KC_G), LSFT_T(KC_H), LT(8,KC_J), LT(10,KC_K), KC_L, KC_SCLN, KC_QUOT, KC_LSFT, KC_Z, KC_X, KC_C, KC_V, LT(7,KC_B), KC_N, KC_M, KC_COMM, KC_DOT, KC_SLSH, KC_LSFT, KC_LCTL, KC_LGUI, TT(6), KC_LALT, LT(1,KC_ENT), LSFT_T(KC_SPC), MO(2), KC_LEFT, KC_DOWN, KC_UP, KC_RGHT),
  /* lower */
	[1] = LAYOUT_plaid_mit(KC_TILD, KC_EXLM, KC_AT, KC_HASH, KC_DLR, KC_PERC, KC_CIRC, KC_AMPR, KC_ASTR, KC_LPRN, KC_RPRN, KC_DEL, KC_TRNS, KC_F1, KC_F2, KC_F3, KC_F4, KC_F5, KC_F6, KC_UNDS, KC_EQUAL, KC_LCBR, KC_RCBR, KC_PIPE, KC_TRNS, KC_F7, KC_F8, KC_F9, KC_F10, KC_F11, KC_F12, KC_MUTE, KC_LT, KC_GT, KC_QUES, KC_QUOT, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, MO(3), LALT(KC_LEFT), KC_VOLD, KC_VOLU, LALT(KC_RGHT)),
  /* raise */
	[2] = LAYOUT_plaid_mit(KC_GRV, KC_1, KC_2, KC_3, KC_4, KC_5, KC_6, KC_7, KC_8, KC_9, KC_0, KC_DEL, KC_TRNS, KC_F1, KC_F2, KC_F3, KC_F4, KC_F5, KC_F6, KC_PMNS, KC_EQUAL, KC_LBRC, KC_RBRC, KC_BSLS, KC_TRNS, KC_F7, KC_F8, KC_F9, KC_F10, KC_F11, KC_F12, KC_MUTE, KC_TRNS, KC_TRNS, KC_BSLS, KC_MPRV, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, MO(3), KC_TRNS, KC_TRNS, KC_MPLY, KC_VOLD, KC_VOLU, KC_MNXT),
  /* adjust */
	[3] = LAYOUT_plaid_mit(KC_TRNS, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, RESET, KC_TRNS, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, RESET, KC_TRNS, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_TRNS, KC_NO, KC_TRNS, KC_NO, KC_TRNS, LCA(KC_DEL), KC_TRNS, KC_NO, KC_NO, KC_NO, EEP_RST),
  /* esc 4 ap2 */
	[4] = LAYOUT_plaid_mit(KC_DEL, LGUI(LCTL(KC_LEFT)), LGUI(LCTL(KC_RIGHT)), LGUI(KC_E), LALT(KC_F4), KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_DEL, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_INS, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO),
  /* s 4 numpad */
	[5] = LAYOUT_plaid_mit(KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_PAST, KC_P7, KC_P8, KC_P9, KC_PMNS, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_MINS, KC_P4, KC_P5, KC_P6, KC_PPLS, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_P1, KC_P2, KC_P3, KC_TRNS, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_P0, KC_PDOT, KC_NO, KC_NO, KC_NO, KC_NO),
  /* mouse - why */
	[6] = LAYOUT_plaid_mit(KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_MS_U, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_MS_L, KC_MS_D, KC_MS_R, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_WH_U, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_TRNS, KC_NO, KC_TRNS, KC_BTN1, KC_TRNS, KC_WH_D, KC_NO, KC_NO, KC_NO),
  /* g - brackets */
	[7] = LAYOUT_plaid_mit(KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_NO, KC_NO, KC_NO, KC_NO, KC_LBRC, KC_RBRC, KC_NO, KC_NO, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_NO, KC_NO, JSARROW, KC_LPRN, KC_RPRN, KC_LCBR, KC_RCBR, KC_NO, KC_TRNS, KC_TRNS, KC_TRNS, KC_NO, KC_NO, KC_NO, KC_NO, KC_LBRC, KC_RBRC, KC_NO, KC_NO, KC_NO, KC_TRNS, KC_TRNS, KC_TRNS, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO),
  /* j - launch */
	[8] = LAYOUT_plaid_mit(KC_TRNS, LGUI(KC_1), LGUI(KC_2), LGUI(KC_E), LGUI(KC_4), LGUI(KC_5), LGUI(KC_6), LGUI(KC_7), LGUI(KC_8), KC_NO, KC_NO, KC_NO, KC_TRNS, KC_TRNS, KC_TRNS, LGUI(KC_3), KC_TRNS, KC_TAB, KC_TRNS, KC_TRNS, KC_LGUI, LGUI(KC_L), KC_LALT, KC_NO, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_NO, KC_NO, KC_NO, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_NO, KC_NO, KC_NO),
  /* d - navj */
	[9] = LAYOUT_plaid_mit(KC_TRNS, KC_TRNS, LCTL(KC_W), KC_TRNS, LCTL(KC_R), LCTL(KC_T), KC_TRNS, KC_PGUP, KC_UP, KC_PGDN, KC_NO, KC_TRNS, KC_TRNS, KC_TRNS, KC_DEL, KC_TRNS, KC_LSFT, LCTL(KC_TAB), KC_HOME, KC_LEFT, KC_DOWN, KC_RGHT, KC_END, LCTL(KC_L), KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, LCTL(KC_V), KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, JSARROW, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_LCTL, LCTL(KC_C), LCTL(KC_X), KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS),
  /* k - ctl  */
	[10] = LAYOUT_plaid_mit(KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_DEL, KC_DEL, KC_BSPC, LALT(KC_LEFT), KC_NO, KC_LCTL, KC_NO, LCTL(KC_L), KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, LCTL(KC_SLSH), KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, LCTL(KC_SPC), KC_NO, KC_NO, KC_NO, KC_NO, KC_NO)
};


// copied fron default


#define LOWER MO(1)
#define RAISE MO(2)

// array of keys considered modifiers for led purposes
// doesn't seem to pickup the LT_ or LSHFT_T keys
// which is confusing - when do they get dealt with?
const uint16_t modifiers[] = {
    KC_LCTL,
    KC_RCTL,
    KC_LALT,
    KC_RALT,
    KC_LSFT,
    KC_RSFT,
    KC_LGUI,
    KC_RGUI,
    LT(1, KC_ENT),
    LSFT_T(KC_F),
    LSFT_T(KC_H),
    LSFT_T(KC_SPC),
    LT(4,KC_ESC), LT(5,KC_S), LT(9,KC_D), LT(7,KC_G), LT(8,KC_J), LT(10,KC_K),
    LOWER,
    RAISE
};

//Setup consts for LED modes
#define LEDMODE_ON 1 //always on
#define LEDMODE_OFF 0 //always off
#define LEDMODE_MODS 2 //On with modifiers
#define LEDMODE_BLINKIN 3 //blinkinlights - % chance toggle on keypress
#define LEDMODE_KEY 4 //On with any keypress, off with key release
#define LEDMODE_ENTER 5 // On with enter key

//Setup config struct for LED
typedef union {
  uint32_t raw;
  struct {
    uint8_t  red_mode :8;
    uint8_t  green_mode :8;
  };
} led_config_t;
led_config_t led_config;

//Set leds to saved state during powerup
void keyboard_post_init_user(void) {
  // set LED pin modes
  // setPinOutput makes them really bright
  // but default might be too dim?
  // too dim for red, but just right for green
  setPinOutput(LED_RED);
  // setPinOutput(LED_GREEN);

  // Call the post init code.
  led_config.raw = eeconfig_read_user();

  if(led_config.red_mode == LEDMODE_ON) {
      writePinHigh(LED_RED);
  }

  if(led_config.green_mode == LEDMODE_ON) {
      writePinHigh(LED_GREEN);
  }
}
 
// EEPROM is getting reset! 
void eeconfig_init_user(void) { 
  led_config.raw = 0;
  led_config.red_mode = LEDMODE_ON;
  // led_config.green_mode = LEDMODE_MODS;
  led_config.green_mode = LEDMODE_ENTER;
  eeconfig_update_user(led_config.raw);
}


void led_keypress_update(uint8_t led, uint8_t led_mode, uint16_t keycode, keyrecord_t *record) {
    switch (led_mode) {
    case LEDMODE_MODS:
        for (int i = 0; i < sizeof(modifiers) / sizeof(modifiers[0]); i++) {
          if (keycode == modifiers[i]) {
            if (record->event.pressed) {
              writePinHigh(led);
            }
            else {
              writePinLow(led);
            }
          }
        }
        break;
    case LEDMODE_BLINKIN:
        if (record->event.pressed) {
          if (rand() % 2 == 1) {
            if (rand() % 2 == 0) {
              writePinLow(led);
            }
            else {
              writePinHigh(led);
            }
          }
        }
        break;
    case LEDMODE_KEY:
        if (record->event.pressed) {
          writePinHigh(led);
          return;
        }
        else {
          writePinLow(led);
          return;
        }
        break;
    case LEDMODE_ENTER:
        if (keycode == KC_ENT) {
          writePinHigh(led);
        }
        else {
          writePinLow(led);
        }
        break;

    }
}

bool process_record_user(uint16_t keycode, keyrecord_t *record) {
  /* If the either led mode is keypressed based, call the led updater
     then let it fall through the keypress handlers. Just to keep 
     the logic out of this procedure */
  if (led_config.red_mode >= LEDMODE_MODS && led_config.red_mode <= LEDMODE_ENTER) {
      led_keypress_update(LED_RED, led_config.red_mode, keycode, record);
  }
  if (led_config.green_mode >= LEDMODE_MODS && led_config.green_mode <= LEDMODE_ENTER) {
      led_keypress_update(LED_GREEN, led_config.green_mode, keycode, record);
  }

  if (keycode == JSARROW && record->event.pressed) {
    SEND_STRING("=>");
  }
  
  return true;
}
